#!/usr/bin/env python
import os 

# Import the environment, functions, and lib directory location
Import('env', 'removemods', 'libdir', 'bindir', 'getlib', 'target',
        'depend', 'dependname', 'cleanstaticlib')
env = env.Clone() 

# get list of source files using Scon's Glob function
sources = Glob('*.f90') + Glob('*.f')
objs = removemods(env.Object(sources))

# build shared library 
lib = env.SharedLibrary(os.path.join(libdir, target), objs, 
                    LIBS=dependname, LIBPATH=libdir)
bin = env.Program(os.path.join(bindir, target), objs, 
                    LIBS=dependname, LIBPATH=libdir)
env.Requires(lib, depend)
env.Requires(bin, depend)
cleanstaticlib(target, lib, env)
Return('lib')